db:
        connection: mydb
        port: 1521
        user: applic
        pwd: name
myconfig:
        prop1: name
        prop2: age
service1:
         port: 8080
service1:
         name: service1
         
